# Rustfmt configuration for FraiseQL v2

brace_style = "SameLineWhere"
# Chains
chain_width = 80
comment_width = 100
# Control flow
control_brace_style = "AlwaysSameLine"
# Edition
edition = "2021"
enum_discrim_align_threshold = 20
# Functions
fn_params_layout = "Tall"
fn_call_width = 80
group_imports = "StdExternalCrate"
hard_tabs = false
# Imports
imports_granularity = "Crate"
match_arm_blocks = true
match_arm_leading_pipes = "Never"
# Match
match_block_trailing_comma = true
# Line width
max_width = 100
# Misc
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
# Structs and enums
struct_field_align_threshold = 20
tab_spaces = 4
use_small_heuristics = "Default"
style_edition = "2024"
# Comments
wrap_comments = true
