name: fraiseql_dart
description: Dart authoring language for FraiseQL with 100% feature parity
version: 1.0.0
publish_to: https://pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
  lints: ^2.1.0

authors:
  - FraiseQL Contributors

homepage: https://github.com/fraiseql/fraiseql
repository: https://github.com/fraiseql/fraiseql
documentation: https://github.com/fraiseql/fraiseql/tree/main/fraiseql-dart
issue_tracker: https://github.com/fraiseql/fraiseql/issues

topics:
  - graphql
  - authorization
  - security
  - schema
